### Numpy 
NumPy is a Python library for numerical and scientific computing. It provides support for multi-dimensional arrays and a wide range of mathematical functions, making it a fundamental tool for data manipulation, analysis, and scientific research in Python. NumPy is often used in combination with other libraries for tasks like data analysis, machine learning, and data visualization.

In [20]:
import numpy as np


In [8]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
array = np.array(list)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
type(array)


numpy.ndarray

In [11]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
array[0]

1

In [13]:
matrix[0]

[1, 2, 3]

In [14]:
matrix[0][1]


2

In [15]:
array[0] + array[1]

3

In [16]:
matrix[0] + matrix[2] 

[1, 2, 3, 7, 8, 9]

In [17]:
matriz = np.array(matrix)


In [18]:
matriz[1,2]


6

In [19]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])