## Dimensions

Arrays with N dimensions

* scalar: dim = 0 scalar - a data

* vector: dim = 1 vector - list of data

* matriz: dim = 2 array - matrix of data

* tensor: dim > 3 tensor - arrays with more dimensions

In [68]:
import numpy as np

A scalar is an element of a field which is used to define a vector space

In [69]:

scalar = np.array(33)
print(scalar)
scalar.ndim

33


0

A vector is a quantity or phenomenon that has two independent properties: magnitude and direction

In [70]:

vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

Matrix, a set of numbers arranged in rows and columns so as to form a rectangular array. The numbers are called the elements, or entries, of the matrix.

Matrix is a list with list inside

In [71]:

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
matrix.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

 Tensors are geometrical objects that describe the linear relationships between geometric, nu- merical, and other tensile vectors.” “The simplest way to imagine a tensor is that it's a vector in a product space

In [72]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

### add or delete dimensions

In [73]:
vector = np.array([1, 2, 3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

expand add a new dimension in array

In [74]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

squeeze method remove the dimensions useless

In [75]:
print(vector)
print(vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2)
vector_2.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]
10
[1 2 3]


1

print(tensor_2.shape) is read as (3, 2, 3)
3 arrays with
2 vectors inside and each vector has
3 scalars inside


In [76]:
tensor_2 = np.array([
    [[1,1,1],[2,2,2]],
    [[3,3,3],[4,4,4]],
    [[5,5,5],[6,6,6]]
    ])
print(tensor_2)
print(tensor_2.ndim)
print(tensor_2.shape)

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]]
3
(3, 2, 3)


In [77]:
expand_2 = np.expand_dims(tensor_2, axis=0)
print(expand_2)
expand_2.ndim, expand_2.shape

[[[[1 1 1]
   [2 2 2]]

  [[3 3 3]
   [4 4 4]]

  [[5 5 5]
   [6 6 6]]]]


(4, (1, 3, 2, 3))

expand_2.ndim, expand_2.shape is read as (4, (3, 1, 2, 3))
4 dimensions

3 tesors with
1 arrays inside and each array with
2 vectors inside and each vector has
3 scalars inside

In [78]:
expand_2 = np.expand_dims(tensor_2, axis=1)
print(expand_2)
expand_2.ndim, expand_2.shape

[[[[1 1 1]
   [2 2 2]]]


 [[[3 3 3]
   [4 4 4]]]


 [[[5 5 5]
   [6 6 6]]]]


(4, (3, 1, 2, 3))