## Arrays Creation

In [2]:
import numpy as np

In [6]:
# list of python, but it is not an arrays for Numpy
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
# In order to create an arrays faster with numpy, use arange method

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# A method highly used to define an structure previusly when the dimension are known
np.zeros((3,10))
# in this case the arrays will have 3 rows with 10 columns and each scalar is a zero.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
# another case is one method
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# The np.linspace function generates an array of numbers that starts at start, ends at stop, and contains num elements equally spaced in that interval.
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [18]:
# The np.eye() function from the NumPy library in Python is used to create an identity matrix, which is a square matrix with ones on the main diagonal and zeros in all other positions.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
#random value - float number
np.random.rand()
np.random.rand(1)
np.random.rand(4)
np.random.rand(4, 4)

array([[0.15053569, 0.89885821, 0.12734098, 0.84029   ],
       [0.59303595, 0.36773613, 0.44715851, 0.4688242 ],
       [0.98983508, 0.97507842, 0.34686369, 0.387587  ],
       [0.7116239 , 0.7010699 , 0.71867328, 0.22612517]])

In [33]:
# randon values with intenger
np.random.randint(1,15)

13

In [35]:
# it creates an arrays with 10 rows and 10 columns, with ramdom values from 1 to 15
np.random.randint(1,15, (10, 10))

array([[12,  1,  1,  3,  3,  1,  3, 11, 11,  6],
       [10,  4,  6,  8,  3,  6, 13,  7, 13, 14],
       [14,  8,  9,  8, 14,  2,  8, 12, 11,  6],
       [13, 12,  3,  5,  2, 11,  4,  1,  7, 14],
       [ 2,  6, 10,  2,  7, 12,  4, 11,  6, 10],
       [ 1,  1,  2, 13, 10,  3, 10,  4,  4,  7],
       [ 1, 11, 10,  7,  2,  4, 11, 13,  1,  3],
       [11,  3, 13, 12, 10, 11, 14, 14, 10,  4],
       [14,  6,  7, 10, 10,  1,  8, 12,  8,  6],
       [14,  1,  1,  9,  6, 13, 12,  2, 11,  4]])