## Shape and Reshape

In [16]:
import numpy as np

In [17]:
array = np.random.randint(1,10,(3,2))
print(array)

[[9 8]
 [1 4]
 [9 1]]


In [18]:
# The shape of an array can be defined as the number of elements in each dimension
array.shape

(3, 2)

In [19]:
# Reshaping means changing the shape of an array. The shape of an array is the number of elements in each dimension. It is not possible to reshape with more or less elements, in this case 6 are the max elemnts allowed
array.reshape(1,6)

array([[9, 8, 1, 4, 9, 1]])

In [20]:
array.reshape(2,3)

array([[9, 8, 1],
       [4, 9, 1]])

In [21]:
# with numpy
np.reshape(array,(1,6))

array([[9, 8, 1, 4, 9, 1]])

In [22]:
array

array([[9, 8],
       [1, 4],
       [9, 1]])

In [23]:
# How to sorg as C Lenguage - it is sorted by rows 9, 8, 1, 4, 9, 1
np.reshape(array,(2,3), 'C')

array([[9, 8, 1],
       [4, 9, 1]])

In [24]:
# How to sorg as Fortrab Lenguage - it is sorted by columns 9, 1, 9, 8, 4, 1
np.reshape(array,(2,3), 'F')

array([[9, 9, 4],
       [1, 8, 1]])