## Main Function

In [71]:
import numpy as np

### Array Structure

Array = (start random number, stop random number, number of elements and structure)  
struture could be: scalar, vector, matrix or tensor

In [72]:
array = np.random.randint(1, 20, 10)
array

array([12,  3, 13, 15,  5, 14, 10,  5, 10,  1])

In [73]:
matrix = array.reshape(2,5)
matrix

array([[12,  3, 13, 15,  5],
       [14, 10,  5, 10,  1]])

In [74]:
# How to know the max number 
array.max()


15

In [75]:
matrix.max()

15

In [76]:
# Find max elements by columns
matrix.max(0)

array([14, 10, 13, 15,  5])

In [77]:
# Find max elements by rows
matrix.max(1)

array([15, 14])

In [78]:
# Find max elements, if there are repeated elements then the first will be selected -  in this case the 2 index array([15, 15, 19,  6, 19,  2,  6, 19, 13, 16]) is 19
array.argmax() 

3

In [79]:
array.min()

1

In [80]:
matrix.argmin(0)

array([0, 0, 1, 1, 1])

In [81]:
matrix.argmin(1)

array([1, 4])

In [82]:
array

array([12,  3, 13, 15,  5, 14, 10,  5, 10,  1])

In [83]:
# distance between min and max numbers
array.ptp()

14

In [84]:
matrix

array([[12,  3, 13, 15,  5],
       [14, 10,  5, 10,  1]])

In [85]:
# distance between min and max numbers by columns
matrix.ptp(0)

array([2, 7, 8, 5, 4])

In [86]:
matrix

array([[12,  3, 13, 15,  5],
       [14, 10,  5, 10,  1]])

In [87]:
# distance between min and max numbers by rows
matrix.ptp(1)

array([12, 13])

In [88]:
array

array([12,  3, 13, 15,  5, 14, 10,  5, 10,  1])

In [89]:
# Percentile 50 is the number in the middle of the arrays when arrays is even, in other hand, when arrays is odd then is arithmetic average of 2 numbers in the middle of array
np.percentile(array, 50)

10.0

In [90]:
np.percentile(array, 0)

1.0

In [91]:
np.percentile(array, 100)

15.0

In [92]:
array.sort()

In [93]:
np.percentile(array, 50)

10.0

In [94]:
np.median(array)

10.0

In [95]:
np.median(matrix,1)

array([ 5., 13.])

In [96]:
np.std(array)

4.686149805543993

In [97]:
np.std(matrix)

4.686149805543993

In [98]:
np.var(array)

21.96

In [99]:
np.var(matrix)

21.96

In [100]:
np.mean(array)

8.8

median is equal to the 50th percentile, however the mean is the athyrmetic mean

In [101]:
# concat

a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [102]:
np.concatenate((a,b),axis=0)

# it does not work because a and b arrays have different dimensions

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
# in order to solve it, apply expan method
b = np.expand_dims(b, axis=0)

In [ ]:
b

array([[5, 6]])

In [ ]:
# now, concatenate method works
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])