## Copy

Copy is usefull when you need to modify or test some changes in a array, however the array father is not modified, but new array is created in a new memory space.

In [2]:
import numpy as np

In [3]:
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
slice_array = array[0:6]
slice_array

array([0, 1, 2, 3, 4, 5])

In [5]:
slice_array[:] = 0
slice_array

array([0, 0, 0, 0, 0, 0])

In [6]:
array

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [7]:
array_copy = array.copy()

In [8]:
array_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [9]:
array_copy[:] = 100


In [10]:
array_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [11]:
array

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])