## Conditions

In [3]:
import numpy as np

In [7]:
# linspace (start, stop, # elements), it ruturns a list with elements with the same space between them
array = np.linspace(1, 10, 10, dtype='int8')
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [8]:
# conditions

array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [9]:
array < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [10]:
boolean_results = array > 5
boolean_results

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [13]:
array[boolean_results]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [15]:
condition = (array > 3) & (array < 8)
condition

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [17]:
array[condition]

array([4, 5, 6, 7], dtype=int8)

In [19]:
# in order to change some elements in array

array
array[condition] = 77


In [20]:
# new array was changed.
array


array([ 1,  2,  3, 77, 77, 77, 77,  8,  9, 10], dtype=int8)

In [21]:
array[array==77]

array([77, 77, 77, 77], dtype=int8)