## Operations

In [2]:
import numpy as np

In [5]:
# Python list
list  = [1, 2]
list

[1, 2]

In [4]:
# Output of python list is duplicate the list
list * 2

[1, 2, 1, 2]

In [7]:
# Using Numpy

array = np.arange(0, 10)
array_2 = array.copy()

In [10]:
# New Array with Numpy
array_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Using Numpy each element is multiplicated by 2
array_2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
array_2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
array_2 - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [13]:
array_2 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [14]:
1 / array_2

/var/folders/5f/8wn5rtw909qbjlpmf_jgrh4h0000gn/T/ipykernel_4212/1888244806.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / array_2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
array_2 ** 2


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
array_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
array + array_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
matrix = array.reshape(2,5)
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
matrix_2 = matrix.copy()
matrix_2


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
matrix + matrix_2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [23]:
matrix * matrix_2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [24]:
matrix_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [27]:
# Second matrix have to be transposed before to apply dot product
matrix_2 = matrix_2.T


In [26]:
# dot product of matrices

np.matmul(matrix, matrix_2)

array([[ 30,  80],
       [ 80, 255]])

In [30]:
# another way to do dot product

matrix @ matrix_2.T

array([[ 30,  80],
       [ 80, 255]])