In [1]:
import numpy as np


In [5]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
array = np.array(list)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
type(array)


numpy.ndarray

In [9]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
array[0]

1

In [11]:
matrix[0]

[1, 2, 3]

In [12]:
matrix[0][1]


2

In [13]:
array[0] + array[1]

3

In [15]:
matrix[0] + matrix[2] 

[1, 2, 3, 7, 8, 9]

In [16]:
matrix[0, 2]


TypeError: list indices must be integers or slices, not tuple

In [17]:
matrix[0,1]

TypeError: list indices must be integers or slices, not tuple

In [18]:
matriz = np.array(matrix)


In [19]:
matriz[1,2]


6

In [20]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
array[0:3]

array([1, 2, 3])